### ISSUE TITLE
Microsoft Employees receiving emails on every opened issue

### ISSUE THREAD

**Issue by lucashuet93** [Microsoft/linguisticreview#427]
Hi,

I've seen a thread opened about this in the past week or so, but it doesn't seem resolved. I'm getting hundreds of emails per day from this repository and it's severely hampering my ability to read my email. If you could please unsubscribe Microsoft employees not involved in this repo that would be great.

Thanks!

**Comment by msftgits** [comment]
Microsoft open source GitHub administrator here to help provide context. There are currently 2,800 employees who are subscribed to this repository. Unfortunately many GitHub users have configured their personal notification preferences to "automatically watch repositories when given push access". 

**You need to do 2 things to solve this permanently:**

1. Change your personal GitHub notification settings to no longer automatically watch repositories. Do this here: https://github.com/settings/notifications

2. Ignore/unsubscribe from this specific repo by going to https://github.com/Microsoft/linguisticreview, selecting the 'Watch' graphic, and choosing 'ignore'.

Here is more information, hoping to get this in one place.

## Background

The person who created this repository unfortunately added "everyone" at Microsoft with GitHub accounts as a repository *administrator*. This is a severe privilege/permission grant and should not be done. This allows anyone at the company essentially to control, edit, even delete the repository. 

After over 7,000+ users received notifications and this came to the Open Source Programs Office's attention, we immediately downgraded the permission level of everyone to read.

While this helps in some situations, unfortunately anyone who has the automatic watch setting on will continue to receive these specific repository notifications forever. An impacted user must ignore/unsubscribe from the mail to stop getting the notifications.

Although we actively block such decisions for repositories today, this has happened ~5 times over the past 7 years.

### Recommended reading

If you are new to GitHub, we strongly recommend that you take the time to get familiar with permission settings and levels. You should allow a very small team administrator access, perhaps a larger team write access to accept pull requests, and most users will be successful contributing to your project by forking, for which they only need read access. Learn more here: https://help.github.com/articles/repository-permission-levels-for-an-organization/

### How we have attempted a technical solution

The Microsoft portal for creating repos does have protections in place: You cannot create a new repository and assign 'Everyone' admin permissions. This was a specific feature implemented by our team.

However, GitHub still allows repo admins to configure other permissions, including giving everyone admin access, and this cannot be prevented. A webhook is generated at the time of such a move, and OSPO has a service connected to the real-time event firehose from GitHub that detects team permission changes; if a team with > 250 people in it is given admin permissions, that permission grant is immediately revoked and downgraded to 'read' only. This is the best technical limitation that can be put in place at this time. Unfortunately anyone subscribed automatically due to their notification settings will _not_ be unsubscribed.

### Opportunities to share feedback with GitHub.com

At the Microsoft scale on GitHub, many features and functions do tend to fall down: permissions are broad, not all users are fully aware of GitHub features, and so accidents do happen. If you feel that there is something that GitHub could do differently, you can always e-mail support@github.com and they will take your feedback and get it to the appropriate contacts.

Specific to this case, similar to how notifications can be routed to different e-mail addresses depending on the organization, it would be great if GitHub would allow configuration of the "automatically" watch setting to be org-specific instead of account-wide. Also, we'd love it if they had protections at the account level against assigning such broad permissions to thousands of people.

## Anything else?

If you have any other questions, you can always e-mail opensource@microsoft.com and someone will try and help. We appologive on behalf of the situation here and hope you can understand the challenges that we all face at the scale of Microsoft's GitHub presence.

## Screenshots to help solve the problem

Here are screenshots of where the key changes are. The account notification settings. Make sure this is **unchecked** for your sanity:

![automatic](https://user-images.githubusercontent.com/9328564/27748237-7bf93cfc-5d83-11e7-88a1-737ca53cb23d.PNG)

This is the 'linguisticreview' repository's "watch" area:

![ignore](https://user-images.githubusercontent.com/9328564/27748243-80d28274-5d83-11e7-9826-14ca39135290.PNG)

_Thanks,
Microsoft GitHub Administrators_
